vpc_varaiable = "10.0.0.0/16"
public_subnet = "10.0.1.0/24"
private_subnet = "10.0.2.0/24"
eg_protocol = "all"
eg_role_no = 100
eg_to_port = 0
eg_from_port = 0
eg_action = "allow"
eg_cidr = "0.0.0.0/0"
in_protocol = "all"
in_role_no = 100
in_to_port = 0
in_from_port = 0
in_action = "allow"
in_cidr = "0.0.0.0/0"

ami = "Your Value"
instance_type = "Your Value"
bucket_name = "Your Value"
outbound ="Your Value"
inbound = "Your Value"